# Generated by Django 3.0.2 on 2020-01-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.IntegerField(null=True),
        ),
    ]
