# Generated by Django 3.0.2 on 2020-01-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='location',
        ),
        migrations.AddField(
            model_name='events',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
