# Generated by Django 3.0.2 on 2020-01-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='img',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
