# Generated by Django 3.0.2 on 2020-01-23 09:54

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200123_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
